### ISSUE TITLE
Error calling Database constructor when using webpack

### ISSUE THREAD

**Issue by karlb** [kripken/sql.js#287]
I'm writing a webapp based on create-react-app and thus using webpack and uglify-js. This worked fine when using sql.js 0.5.0, but after upgrading to 1.0.0 I get the following error when calling `new SQL.Database`:

```
sql_js__WEBPACK_IMPORTED_MODULE_1___default.a.Database is not a constructor
```

Are there any changes between these versions that I need to take care of? Any explanations what's going on here are welcome!

**Comment by lovasoa** [comment]
Where does your `Database` object come from ? Did you follow [the instructions in the readme](https://github.com/kripken/sql.js#upgrading-from-0x-to-1x) ?


```js
  initSqlJs({ locateFile: filename => `/path/to/assets/${filename}` }).then(function(SQL){
    var db = new SQL.Database();
    //...
  });
```

**Comment by karlb** [comment]
Sorry, I missed the upgrading info in the readme. I was looking for `ChangeLog` file instead.

Contrary to the readme, requiring `sql-wasm.js` fails for me when run under nodejs:
```js
var initSqlJs = require('sql-wasm.js');
  initSqlJs().then(function(SQL){
  var db = new SQL.Database();
});

Error: Cannot find module 'sql-wasm.js'
```
while requiring `sql.js` works.

Using the same approach inside my webpacked application unfortunately does not work but yields
```
Wasm decoding failed: expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
```
instead. I'll see if I can find out what's happening, here.

**Comment by lovasoa** [comment]
The key part is `{ locateFile: filename => `/path/to/assets/${filename}` }`. You have to tell it where to find the wasm file. When you install the package with node, it is in `node_modules/sql.js/dist`

**Comment by karlb** [comment]
In the readme only the example using the `<script>` tag used the `locateFile`, so I thought that part does not apply when using `require`. I still don't feel at home in the modern JS world, so I lack a proper understanding of how all these approaches map to each other.

After linking `node_modules/sql.js/dist` into the directory with the public static assets (`public` in my case), I could load it without problems using `locateFile`. Too bad that I didn't get a clearer error message before, but I guess that's what I should expect when the web server returns 200 OK for all URLs.

Thanks a lot for your help!

**Comment by lovasoa** [comment]
If you think our README could be improved, feel free to make a pull request. That will be very appreciated, and I'll be sure to review it.
